[greeter]
background=#1a1a2e
theme-name=WhiteSur-Light
icon-theme-name=WhiteSur
cursor-theme-name=WhiteSur-cursors
font-name=Inter 11
indicators=~host;~spacer;~clock;~spacer;~power
clock-format=%H:%M  %a %d %b
